version: "2"
services:
  app:
    container_name: boardservice_app
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: boardservice_mongo
    image: mongo
    volumes:
      - ./data:/data/db

